=== tieulonglanh/caodangyhanam/Data/chords/data/chords.dtd
<!ELEMENT app ( capo, fr, f1, f2, f3, f4, s1, s2, s3, s4, s5, s6 ) >
<!ATTLIST app id NMTOKEN #REQUIRED >

<!ELEMENT apps ( app ) >

<!ELEMENT capo ( str, pos ) >

<!ELEMENT chord ( name, apps ) >
<!ATTLIST chord id NMTOKEN #REQUIRED >

<!ELEMENT chords ( chord ) >

<!ELEMENT f1 ( str, pos ) >

<!ELEMENT f2 ( str, pos ) >

<!ELEMENT f3 ( str, pos ) >

<!ELEMENT f4 ( str, pos ) >

<!ELEMENT fr ( #PCDATA ) >

<!ELEMENT name ( #PCDATA ) >

<!ELEMENT pos ( #PCDATA ) >

<!ELEMENT s1 ( #PCDATA ) >

<!ELEMENT s2 ( #PCDATA ) >

<!ELEMENT s3 ( #PCDATA ) >

<!ELEMENT s4 ( #PCDATA ) >

<!ELEMENT s5 ( #PCDATA ) >

<!ELEMENT s6 ( #PCDATA ) >

<!ELEMENT str ( #PCDATA ) >

=== tieulonglanh/caodangyhanam/en/Data/chords/data/chords.xml
<?xml version="1.0" encoding="iso-8859-1"?>
<!DOCTYPE chords SYSTEM "chords.dtd">

 <chords>
   <chord id="1">
     <name>C</name>
     <apps>
       <app id ="1">	   	
	   <capo>
	   	<str>0</str>
		<pos>0</pos>
	   </capo>
	   <fr>1</fr>
	   <f1>
	   	<str>2</str>
		<pos>1</pos>
	   </f1>
	   <f2>
	   	<str>4</str>
		<pos>2</pos>
	   </f2>
	   <f3>
	   	<str>5</str>
		<pos>3</pos>
	   </f3>
	   <f4>
	   	<str>0</str>
		<pos>0</pos>
	   </f4>
	   <s1>0</s1>
	   <s2>0</s2>
	   <s3>0</s3>
	   <s4>0</s4>
	   <s5>1</s5>
	   <s6>-1</s6>
	   </app>
     </apps>
   </chord></chords>
